version: '3.1'

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /tdd-dev/library-index/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  mongoku :
    image: huggingface/mongoku
    depends_on:
      - mongo
    ports:
      - 8081:3100
    environment:
      MONGOKU_DEFAULT_HOST: mongodb://admin:password@mongo:27017/